---
title: "Meeting Information"
date: "26th - 28th of March 2024"
output:
  html_document:
    toc: false
    number_sections: false
    theme: cosmo
fontsize: 14pt
---

## What is ARCANI

The ARCANI -- Accelerating Research Collaboration between
Artificial and Natural Intelligences -- project is led by
Erica Cartmill, Jacob Foster and Pranab Das.  It is funded
by the NSF to connect existing networks studying
intelligence in different forms to examine what the next
frontiers of research might be. Details on the project can
be found here: 

<a href="https://www.arcanigroup.org/" target="_blank">ARCANI GROUP</a>

At this meeting we have work to do, and an exciting
opportunity.  In 2025 we will be able to apply to the NSF to
continue ARCANI as a network of networks for a further two
years if there is benefit and need. We need to leave this
meeting with materials for a white paper discussing WHAT are
the gaps in knowledge, WHO can help us close those gaps, HOW
can sustainable collaboration in the ARCANI network close
those gaps.  Hence the structured discussions in our
workshop.

## Venue and campus map

Our meeting will be held in rooms 330-331 of 17 Wallys Walk
in the Michael Kirby Law building.  Maps for Macquarie
University can be found here:
  
<a href="https://www.mq.edu.au/__data/assets/pdf_file/0005/1236317/MQ-Campus_map_2022-10.pdf" target="_blank">Campus Map</a>

The Michael Kirby Building is labelled and is in the exact
centre of campus.  Cafes and restaurants can be found
around the Central Courtyard immediately to the north of
the Michael Kirby Building.

## Getting to Macquarie

Macquarie University is located on Sydney’s north shore
about 17km north of the city centre and 27kn north of the
airport. Macquarie University has a dedicated metro station
(marked on the south east of the map).  This is the easiest
way to get to campus.  Train schedules and routes can be
found at the Transport NSW website.

<a href="https://transportnsw.info/" target="_blank">NSW Transport</a>

On trains and buses in Sydney fares are paid by either opal
card or a credit card (see details on the transportnsw
website. For international visitors Uber operates in Sydney,
but be aware an Uber from the airport will cost about
AU$100.

## Hotel details

For those I have reserved hotel rooms for, our hotel booking
is with the Mercure Macquarie Park at 81 Talavera Road North
Ryde NSW 2113. It’s marked on the campus map (north east)
and an easy walk to our venue.

## Presenter information

The room is equipped with a digital projector connected to a
PC and with an  HDMI connector to plug  in a laptop.
Presenters can either upload a presentation to the resident
PC (please bring your presentation on your own USB) or
connect a laptop directly.  Please bring whatever dongle you
will need to connect to HDMI.

The intent of all talks is to give us plenty of time for
discussion.  For the long talks (James and Michael) I have
in mind 30 mins of discussion. For the 25 minute talks can
speakers please leave five mins for discussion and aim to
talk for 20 mins. For the 15 min talks - please leave five
mins for discussion and aim to speak for 10. 

## Discussions

We have created this simple github website to capture ideas
from our discussions.  

<a href="https://crossley.github.io/ARCANI/" target="_blank">https://crossley.github.io/ARCANI/</a>

In the navigation bar of this page you will find the
following links:

- Meeting Outline
- Meeting information
- Discussion

On the discussino page you will find a page for each of our
discussions with instructions therein.  You will need to
sign up to github (or log in if you already have an account)
to comment.  You can sign up/log in through the website.
Note you will only need the free version of github.  

Please make notes as the discussion is going on. Capture all
ideas, personal or group. These will go on to fuel the white
paper we will be developing after the workshop. Feel free to
comment on, add to, augment, and add reactions to other
people’s posts. Think of this as a high-functional reddit
environment. That means - play nice. 

### WHAT are the gaps in knowledge? 

What is limiting progress in AI and robotics?  What don’t we
understand about animal intelligence? What would it mean to
make AI more biomorphic or neuromorphic? What are the
alternatives to backpropagation through time?  What
questions when answered would have the biggest impact?

The outcome we need from this discussion is a list of well
defined questions (with possible subquestions) that a
network like ARCANI could progress over the next three
years. The full ARCANI network is global and expansive
covering computing, robotics, pure and applied mathematics,
philosophy, psychology, comparative cognition and
neuroscience. It’s a powerful team, so we need to think big
and bold.

### WHO can help us close the knowledge gaps?

This is a data collection exercise over an extended coffee
break.  We need to know who could help us with the questions
identified in the WHAT discussion. To recommend an
individual please give us a Name, an Affiliation, an Email,
a brief statement about what makes this person valuable and
a brief statement about how well you know this person.
Personal connections with the current team will make it
easier to follow up. 

### HOW can sustainable collaboration in the ARCANI network close those gaps

This is brainstorming HOW we should best use the resources
of ARCANI (if granted) to realise the projects proposed in
the what discussion.  Do we need regular workshops? Do we
need extended working parties? Do we need to fund exchanges
between labs? Do we need bespoke digital resources? Often
our biggest barrier to research is time? Can we use ARCANI
to free time? 
